const data = {
    english: [
        'The Amazon Rainforest is home to over 390 billion individual trees, representing more than 16,000 species.',
        'A single teaspoon of soil can contain billions of microorganisms, including bacteria, fungi, and protozoa.',
        'The blue whale is the largest animal on Earth, with a tongue that can weigh as much as an elephant.',
        'A honeybee can fly at speeds of up to 15 miles per hour and beat its wings over 200 times per second.',
        'The mimic octopus can impersonate the appearance and behaviors of other marine animals to evade predators.',
        "The world's largest living organism is a fungus in Oregon's Malheur National Forest, spanning over 2,385 acres.",
        'Polar bears have a layer of transparent fur that appears white, but their skin is actually black to absorb heat.',
        'The Venus flytrap is a carnivorous plant native to the southeastern United States that can count to trap prey.',
        'The African elephant has the largest brain of any land animal, weighing up to 11 pounds.',
        'Giraffes have a unique blood pressure regulation system in their necks to prevent fainting when bending down to drink water.',
        'The Great Barrier Reef is the largest coral reef system in the world, stretching over 1,400 miles.',
        'The monarch butterfly migrates thousands of miles from North America to Mexico each year.',
        'A group of flamingos is called a flamboyance, and they are known for their vibrant pink feathers.',
        "The northern lights, or aurora borealis, are caused by charged particles from the sun colliding with Earth’s atmosphere.",
        'Sea otters hold hands while sleeping to keep from drifting apart and losing each other.',
        'Hummingbirds are the only birds that can fly backwards, thanks to their unique wing structure.',
        'The archerfish shoots jets of water at insects above the surface to knock them into the water and eat them.',
        'A single honeybee will only produce approximately 1/12th of a teaspoon of honey in its lifetime.',
        'The corpse flower, also known as the titan arum, is the largest flower in the world and emits a foul odor when in bloom.',
        'The narwhal, often referred to as the unicorn of the sea, has a long tusk that is actually a tooth protruding from its upper lip.',
        'The platypus is one of the few mammals that lays eggs instead of giving birth to live young.',
        'Sloths can rotate their heads almost 270 degrees due to their unique neck anatomy.',
        'The humpback whale produces intricate songs that can travel for hundreds of miles underwater.',
        'Bamboo is one of the fastest-growing plants in the world, with some species growing up to 35 inches per day.',
        'The pistol shrimp is capable of creating a sonic boom underwater with its snapping claw, stunning prey.',
        'Peregrine falcons are the fastest animals on Earth, reaching speeds of over 240 miles per hour during a dive.',
        "The snow leopard's tail can grow up to 3 feet long and is used for balance and as a blanket in cold weather.",
        'The Venus flytrap can close its trap in just 1/10th of a second when triggered by prey.',
        'The binturong, also known as the bearcat, emits a scent similar to buttered popcorn.',
        'Fireflies produce light through a chemical reaction in their abdomen, a process called bioluminescence.'
    ],
    german: [
        'Die Erde ist der einzige bekannte Planet im Sonnensystem, auf dem flüssiges Wasser in großen Mengen vorkommt.',
        'Unter der Oberfläche der Erde erstreckt sich ein riesiges Netzwerk von Höhlen, einige der längsten sind mehrere Hundert Kilometer lang.',
        'Die Erde hat einen unsichtbaren Schutzschild: Das Magnetfeld schützt uns vor gefährlicher Sonnenstrahlung und Weltraumteilchen.',
        'In der Antarktis gibt es einen Ort namens Blood Falls, an dem rotes, eisenhaltiges Wasser aus einem Gletscher fließt.',
        'Die Erde hat mehr als 3 Billionen Bäume, die den Sauerstoff produzieren, den wir atmen.',
        'Es gibt einen Ort in Mexiko, der als "Höhle der Kristalle" bekannt ist und die größten Kristalle der Welt beherbergt.',
        'Die Erde ist nicht perfekt rund, sondern leicht abgeflacht. Durch die Rotation entsteht eine leichte Ausbuchtung am Äquator.',
        'Im Marianengraben im Pazifischen Ozean liegt der tiefste Punkt der Erde, der Challenger Deep, mit einer Tiefe von etwa 10.994 Metern.',
        'Die Atmosphäre der Erde enthält genug Luft, um jeden Menschen auf dem Planeten 7 Millionen Jahre lang atmen zu lassen.',
        'Die Erde wird von etwa 8,7 Millionen Arten bewohnt, von denen jedoch nur etwa 1,2 Millionen bisher entdeckt und beschrieben wurden.',
        'Das Gepard ist das schnellste Landtier der Welt und kann Geschwindigkeiten von bis zu 120 km/h erreichen.',
        'Die Antarktis ist der kälteste, windigste und trockenste Kontinent der Erde und beheimatet zahlreiche Pinguinarten.',
        'Die Mangrovenwälder sind wichtige Ökosysteme an der Küste und dienen als Kinderstube für viele Fischarten.',
        'Das Great Barrier Reef vor der Küste Australiens ist das größte Korallenriffsystem der Welt und bietet einen Lebensraum für eine Vielzahl von Meereslebewesen.',
        'Der Kolibri kann seinen Herzschlag auf bis zu 1200 Schläge pro Minute beschleunigen, um den Energiebedarf beim Fliegen zu decken.',
        'Der Koala ernährt sich hauptsächlich von Eukalyptusblättern und verbringt bis zu 20 Stunden am Tag mit Schlafen.',
        'Die Arktis ist der Lebensraum für eine Vielzahl von Arten, darunter Eisbären, Robben und Walrosse.',
        'Die Wanderung der Gnus in der Serengeti ist eine der größten Tierwanderungen der Welt und ein beeindruckendes Naturschauspiel.',
        'Der Regenwald im Amazonasbecken ist die Heimat von Millionen von Pflanzen- und Tierarten, von denen viele noch unentdeckt sind.',
        'Der Feldhase kann bis zu 70 km/h schnell laufen und ist bekannt für seine akrobatischen Sprünge.',
        'Die Tiefsee ist der größte Lebensraum der Erde und beheimatet eine Vielzahl faszinierender Kreaturen.',
        'Die Sahara ist nicht nur die größte heiße Wüste der Welt, sondern auch eine der trockensten Regionen.',
        'Der Rotfuchs ist in vielen Teilen der Welt verbreitet und kann sich gut an verschiedene Lebensräume anpassen.',
        'Die Sonnenblume dreht sich im Laufe des Tages so, dass sie stets der Sonne zugewandt ist, ein Phänomen namens Heliotropismus.',
        'Der Polarwolf hat ein dickes Fell und kurze Ohren, um sich an die extremen Bedingungen der Arktis anzupassen.',
        'Die Galápagosinseln sind berühmt für ihre einzigartige Tierwelt, darunter die Riesenschildkröten und Fregattvögel.',
        'Die Berggorillas leben in den Bergwäldern Zentralafrikas und sind stark gefährdet aufgrund von Lebensraumverlust und Wilderei.',
        'Die Korallenriffe sind die "Regenwälder des Meeres" und bieten Lebensraum für eine unglaubliche Vielfalt an Meereslebewesen.',
        'Der Eisberg, der von der Antarktis abbricht, kann die Größe eines kleinen Landes erreichen und ist ein Zeichen des Klimawandels.',
        'Der Tiger ist die größte Katzenart der Welt und ein Symbol für Stärke, Eleganz und Wildheit.'
    ]
}

export default data;
